### ISSUE TITLE
Update How to use it section

### ISSUE THREAD

**Issue by asadm** [asadm/chota#3]
Update the readme.md's "how to use it" section. The steps are roughly:
- Add the following workflow file to your repo:
```
name: Chota Action

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]

jobs:
  branch-actions:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: asadm/chota@3b117de11ebc90e7117895fbad57203c940cba05
      with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SERP_API_KEY: ${{ secrets.SERP_API_KEY }}
```

- From repo settings > actions, toggle "Workflow permissions" to read/write (expand on this after searching on google)

- Sign up and get OpenAI API key and add it to repo settings > secrets (also research on this)

- Sign up to https://serpapi.com/ and also add api key to repo settings (expand on this)

- Next create a new issue and label it "chota" and then describe what you want Chota to do.
